import type { Invoice, InvoiceStats, Schedule, InvoiceMode } from '@/types'

// ── Stats per mode ────────────────────────────────────────────────────────────
export const MOCK_STATS: Record<InvoiceMode, InvoiceStats> = {
  AR: { total: 174, valid_count: 59, invalid_count: 2,  inprogress_count: 1,  error_count: 0, blank_count: 112, submitted_count: 8,  processing_count: 4 },
  AP: { total: 98,  valid_count: 41, invalid_count: 7,  inprogress_count: 5,  error_count: 3, blank_count: 42,  submitted_count: 12, processing_count: 9 },
}

// ── AR invoices ───────────────────────────────────────────────────────────────
const AR_BUYERS    = ['MUFG Bank (Malaysia)', 'N2N CONNECT BERHAD', 'MALAYAN BANKING BE', 'BANK RAKYAT', 'SUMITOMO MITSUI BA']
const AR_SUPPLIERS = ['IPC Information Systems (A)', 'IPC Information Systems (B)', 'IPC Information Systems (C)', 'IPC Systems Sdn Bhd', 'IPC Tech Solutions']
const AR_CITIES    = ['Kuala Lumpur', 'Petaling Jaya', 'Shah Alam', 'Cyberjaya', 'Putrajaya']
const AR_STATUSES  = ['Valid','Valid','Invalid','InProgress','Valid','Submitted','Processing','Error'] as const

export const MOCK_AR_INVOICES: Invoice[] = Array.from({ length: 40 }, (_, i) => {
  const status = AR_STATUSES[i % 8]
  return {
    invoice_id:   `AR-2025-${String(i + 1000).padStart(5, '0')}`,
    issue_date:   `2025-01-${String((i % 28) + 1).padStart(2, '0')}`,
    issue_time:   `${String(8 + (i % 10)).padStart(2, '0')}:${String(i * 3 % 60).padStart(2, '0')}:00`,
    invoice_type_code: i % 3 === 0 ? '02' : '01',
    list_version_id: '1.0',
    document_currency_code: 'MYR',
    tax_currency_code: 'MYR',
    supplier_registration_name: AR_SUPPLIERS[i % 5],
    supplier_telephone: '+60312345678',
    supplier_email: 'ar@ipc.com.my',
    supplier_city_name: 'Kuala Lumpur',
    supplier_postal_zone: '50480',
    supplier_country_subentity_code: 'MY-14',
    supplier_address_line: 'Level 10, Menara IPC',
    supplier_identificationcode: 'MY',
    supplier_country_list_id: 'ISO3166-1',
    supplier_country_list_agency_id: '6',
    supplier_additional_account_id: 'C1234567890',
    supplier_scheme_agency_name: 'CertEX',
    supplier_industry_classification_code: '62010',
    supplier_industry_name: 'Computer programming',
    partyidentification_id_1: `TIN-AR-${i}`,
    partyidentification_id_1_scheme: 'TIN',
    partyidentification_id_2: `BRN-AR-${i}`,
    partyidentification_id_2_scheme: 'BRN',
    partyidentification_id_3: 'NA',
    partyidentification_id_3_scheme: 'SST',
    partyidentification_id_4: 'NA',
    partyidentification_id_4_scheme: 'TTX',
    customer_registration_name: AR_BUYERS[i % 5],
    customer_telephone: '+60398765432',
    customer_email: 'buyer@bank.com.my',
    customer_city_name: AR_CITIES[i % 5],
    customer_postal_zone: String(50000 + i * 100),
    customer_country_subentity_code: 'MY-14',
    customer_address_line: `Level ${i + 1}, Menara ${AR_BUYERS[i % 5].split(' ')[0]}`,
    customer_country_code: 'MY',
    customer_country_list_id: 'ISO3166-1',
    customer_country_list_agency_id: '6',
    customer_partyidentification_id_1: `CTIN${i}`,
    customer_partyidentification_id_1_scheme: 'TIN',
    customer_partyidentification_id_2: `CBRN${i}`,
    customer_partyidentification_id_2_scheme: 'BRN',
    customer_id: `CUST-AR-${i + 1000}`,
    payment_terms_note: '30 days net',
    tax_total_amount: parseFloat(((i + 1) * 180).toFixed(2)),
    tax_total_currency: 'MYR',
    tax_subtotal_taxable_amount: parseFloat(((i + 1) * 2000).toFixed(2)),
    tax_subtotal_taxable_currency: 'MYR',
    tax_subtotal_tax_amount: parseFloat(((i + 1) * 180).toFixed(2)),
    tax_subtotal_tax_currency: 'MYR',
    tax_category_id: '01',
    tax_scheme_id: 'OTH',
    tax_scheme_scheme_id: 'UN/ECE 5153',
    tax_scheme_agency_id: '6',
    line_extension_amount: parseFloat(((i + 1) * 2000).toFixed(2)),
    line_extension_currency: 'MYR',
    tax_exclusive_amount: parseFloat(((i + 1) * 2000).toFixed(2)),
    tax_exclusive_currency: 'MYR',
    tax_inclusive_amount: parseFloat(((i + 1) * 2180).toFixed(2)),
    tax_inclusive_currency: 'MYR',
    allowance_total_amount: 0,
    allowance_currency: 'MYR',
    charge_total_amount: 0,
    charge_currency: 'MYR',
    payable_rounding_amount: 0,
    payable_rounding_currency: 'MYR',
    payable_amount: parseFloat(((i + 1) * 2180).toFixed(2)),
    payable_currency: 'MYR',
    created_at: '2025-01-17T10:00:00',
    QR_CODE: '',
    STATUS: status,
    uuid: `ar-uuid-${i}`,
    e_invoice_status: status,
    submissionUid: `AR-SUB-${i}`,
    e_invoice_error: i % 8 === 7 ? 'Validation failed: missing tax code' : '',
    invoice_trx_id: String(410000 + i),
    invoice_update_status: 'Updated',
    format: 'JSON',
    documenthash: `arhash${i}`,
    base64document: '',
    validationerror: '',
    billing_invoice_id: '',
    billing_invoice_uuid: '',
    additional_doc_id: '',
    d: 'AR_FIELD_D',
    a: 'AR_FIELD_A',
    b: 'AR_FIELD_B',
  }
})

// ── AP invoices ───────────────────────────────────────────────────────────────
const AP_VENDORS  = ['Telekom Malaysia Bhd', 'Tenaga Nasional Bhd', 'Axiata Group Bhd', 'Petronas Gas Bhd', 'MISC Bhd']
const AP_BUYERS   = ['IPC Information Systems (A)', 'IPC Information Systems (B)', 'IPC Tech Solutions', 'IPC Systems Sdn Bhd', 'IPC Holdings Bhd']
const AP_CITIES   = ['Bangsar', 'Mont Kiara', 'KLCC', 'Damansara', 'Subang Jaya']
const AP_STATUSES = ['Valid','Submitted','Invalid','Processing','Valid','Error','Valid','InProgress'] as const

export const MOCK_AP_INVOICES: Invoice[] = Array.from({ length: 40 }, (_, i) => {
  const status = AP_STATUSES[i % 8]
  return {
    invoice_id:   `AP-2025-${String(i + 2000).padStart(5, '0')}`,
    issue_date:   `2025-02-${String((i % 28) + 1).padStart(2, '0')}`,
    issue_time:   `${String(9 + (i % 8)).padStart(2, '0')}:${String(i * 7 % 60).padStart(2, '0')}:00`,
    invoice_type_code: i % 4 === 0 ? '03' : '01',
    list_version_id: '1.1',
    document_currency_code: 'MYR',
    tax_currency_code: 'MYR',
    supplier_registration_name: AP_VENDORS[i % 5],
    supplier_telephone: '+60387654321',
    supplier_email: 'vendor@supplier.com.my',
    supplier_city_name: AP_CITIES[i % 5],
    supplier_postal_zone: String(60000 + i * 50),
    supplier_country_subentity_code: 'MY-14',
    supplier_address_line: `Block ${i + 1}, Plaza ${AP_VENDORS[i % 5].split(' ')[0]}`,
    supplier_identificationcode: 'MY',
    supplier_country_list_id: 'ISO3166-1',
    supplier_country_list_agency_id: '6',
    supplier_additional_account_id: 'V9876543210',
    supplier_scheme_agency_name: 'CertEX',
    supplier_industry_classification_code: i % 2 === 0 ? '35110' : '61200',
    supplier_industry_name: i % 2 === 0 ? 'Electric power generation' : 'Wired telecom activities',
    partyidentification_id_1: `TIN-AP-${i}`,
    partyidentification_id_1_scheme: 'TIN',
    partyidentification_id_2: `BRN-AP-${i}`,
    partyidentification_id_2_scheme: 'BRN',
    partyidentification_id_3: `SST-AP-${i}`,
    partyidentification_id_3_scheme: 'SST',
    partyidentification_id_4: 'NA',
    partyidentification_id_4_scheme: 'TTX',
    customer_registration_name: AP_BUYERS[i % 5],
    customer_telephone: '+60312345678',
    customer_email: 'ap@ipc.com.my',
    customer_city_name: 'Petaling Jaya',
    customer_postal_zone: '47810',
    customer_country_subentity_code: 'MY-10',
    customer_address_line: 'Level 5, IPC Tower, PJ',
    customer_country_code: 'MY',
    customer_country_list_id: 'ISO3166-1',
    customer_country_list_agency_id: '6',
    customer_partyidentification_id_1: 'CTIN-IPC',
    customer_partyidentification_id_1_scheme: 'TIN',
    customer_partyidentification_id_2: 'CBRN-IPC',
    customer_partyidentification_id_2_scheme: 'BRN',
    customer_id: `CUST-AP-${i + 2000}`,
    payment_terms_note: '45 days net',
    tax_total_amount: parseFloat(((i + 1) * 95).toFixed(2)),
    tax_total_currency: 'MYR',
    tax_subtotal_taxable_amount: parseFloat(((i + 1) * 1050).toFixed(2)),
    tax_subtotal_taxable_currency: 'MYR',
    tax_subtotal_tax_amount: parseFloat(((i + 1) * 95).toFixed(2)),
    tax_subtotal_tax_currency: 'MYR',
    tax_category_id: '01',
    tax_scheme_id: 'OTH',
    tax_scheme_scheme_id: 'UN/ECE 5153',
    tax_scheme_agency_id: '6',
    line_extension_amount: parseFloat(((i + 1) * 1050).toFixed(2)),
    line_extension_currency: 'MYR',
    tax_exclusive_amount: parseFloat(((i + 1) * 1050).toFixed(2)),
    tax_exclusive_currency: 'MYR',
    tax_inclusive_amount: parseFloat(((i + 1) * 1145).toFixed(2)),
    tax_inclusive_currency: 'MYR',
    allowance_total_amount: i % 5 === 0 ? 50 : 0,
    allowance_currency: 'MYR',
    charge_total_amount: 0,
    charge_currency: 'MYR',
    payable_rounding_amount: 0,
    payable_rounding_currency: 'MYR',
    payable_amount: parseFloat(((i + 1) * 1145).toFixed(2)),
    payable_currency: 'MYR',
    created_at: '2025-02-01T09:00:00',
    QR_CODE: '',
    STATUS: status,
    uuid: `ap-uuid-${i}`,
    e_invoice_status: status,
    submissionUid: `AP-SUB-${i}`,
    e_invoice_error: i % 8 === 5 ? 'Duplicate invoice detected' : '',
    invoice_trx_id: String(520000 + i),
    invoice_update_status: 'Pending',
    format: 'JSON',
    documenthash: `aphash${i}`,
    base64document: '',
    validationerror: '',
    billing_invoice_id: '',
    billing_invoice_uuid: '',
    additional_doc_id: '',
    d: 'AP_FIELD_D',
    a: 'AP_FIELD_A',
    b: 'AP_FIELD_B',
  }
})

export const MOCK_INVOICES: Record<InvoiceMode, Invoice[]> = {
  AR: MOCK_AR_INVOICES,
  AP: MOCK_AP_INVOICES,
}

export const MOCK_SCHEDULES: Schedule[] = [
  { id: 'SCH-001', name: 'Monthly MUFG Invoices',  description: 'Auto-generate monthly invoices for MUFG Bank',  customer_name: 'MUFG Bank (Malaysia)', customer_id: 'CUST-1000', invoice_type: '01', mode: 'AR', status: 'ongoing',  frequency: 'monthly',   start_date: '2025-01-01', end_date: '2025-12-31', next_run: '2025-05-01', last_run: '2025-04-01', total_invoices: 45, successful: 44, failed: 1, created_by: 'admin@ipc.com',   created_at: '2024-12-15T09:00:00' },
  { id: 'SCH-002', name: 'Weekly N2N Connect',      description: 'Weekly billing for N2N Connect BERHAD',         customer_name: 'N2N CONNECT BERHAD',   customer_id: 'CUST-1001', invoice_type: '01', mode: 'AR', status: 'ongoing',  frequency: 'weekly',    start_date: '2025-01-06', end_date: '2025-06-30', next_run: '2025-04-28', last_run: '2025-04-21', total_invoices: 16, successful: 16, failed: 0, created_by: 'admin@ipc.com',   created_at: '2025-01-01T09:00:00' },
  { id: 'SCH-003', name: 'Daily Telekom AP',         description: 'Daily AP sync for Telekom Malaysia',            customer_name: 'Telekom Malaysia Bhd', customer_id: 'CUST-2000', invoice_type: '02', mode: 'AP', status: 'ongoing',  frequency: 'daily',     start_date: '2025-03-01', end_date: '2025-04-30', next_run: '2025-04-26', last_run: '2025-04-25', total_invoices: 56, successful: 54, failed: 2, created_by: 'ops@ipc.com',     created_at: '2025-02-28T10:00:00' },
  { id: 'SCH-004', name: 'Q1 Bank Rakyat Batch',    description: 'Quarterly batch for Bank Rakyat',               customer_name: 'BANK RAKYAT',          customer_id: 'CUST-1003', invoice_type: '01', mode: 'AR', status: 'finished', frequency: 'quarterly', start_date: '2025-01-01', end_date: '2025-03-31', next_run: '',           last_run: '2025-03-31', total_invoices: 12, successful: 12, failed: 0, created_by: 'finance@ipc.com', created_at: '2024-12-20T09:00:00' },
  { id: 'SCH-005', name: 'TNB Annual AP',            description: 'Annual AP invoicing for Tenaga Nasional',       customer_name: 'Tenaga Nasional Bhd',  customer_id: 'CUST-2001', invoice_type: '01', mode: 'AP', status: 'finished', frequency: 'monthly',   start_date: '2024-01-01', end_date: '2024-12-31', next_run: '',           last_run: '2024-12-31', total_invoices: 12, successful: 11, failed: 1, created_by: 'admin@ipc.com',   created_at: '2023-12-15T09:00:00' },
  { id: 'SCH-006', name: 'Q3 MUFG AR Batch',        description: 'Upcoming Q3 AR batch for MUFG',                 customer_name: 'MUFG Bank (Malaysia)', customer_id: 'CUST-1000', invoice_type: '01', mode: 'AR', status: 'upcoming', frequency: 'quarterly', start_date: '2025-07-01', end_date: '2025-09-30', next_run: '2025-07-01', last_run: '',           total_invoices: 0,  successful: 0,  failed: 0, created_by: 'admin@ipc.com',   created_at: '2025-04-20T09:00:00' },
  { id: 'SCH-007', name: 'H2 Axiata AP Weekly',     description: 'AP weekly schedule for Axiata second half',     customer_name: 'Axiata Group Bhd',     customer_id: 'CUST-2002', invoice_type: '01', mode: 'AP', status: 'upcoming', frequency: 'weekly',    start_date: '2025-07-07', end_date: '2025-12-31', next_run: '2025-07-07', last_run: '',           total_invoices: 0,  successful: 0,  failed: 0, created_by: 'ops@ipc.com',     created_at: '2025-04-18T09:00:00' },
]
